"""What may replace a model that is currently driving a fire."""

import math

import pytest

from controller.model_promotion import (
    PROMOTION_BOUNDS,
    braking_distance,
    effective_tau,
    evaluate,
    longest_braking_distance,
    steady_state_at_full_fire,
)

GOOD = dict(C_c=2520.0, h_amb=0.224, T_amb=20.0, theta=93.0, n_delay=4, K_Q=6.95, sigma=1.4e-9)
INCUMBENT = dict(GOOD, C_c=2000.0, h_amb=0.30)  # tau 6667 vs candidate 11250
HORIZON = dict(n_horizon=144, t_step=25.0)

#: controller/update_mpc.py's fit to tests/unit/mpc/fixtures/
#: mak_cook_2026-08-02.csv -- the 450 F cook that overshot by 70 F. Written out
#: rather than refitted here: this file must stay runnable without scipy or the
#: fixture, and a number regenerated by the code under test could not pin what
#: that code produces. Regenerate with
#: `python -m controller.update_mpc tests/unit/mpc/fixtures/mak_cook_2026-08-02.csv --json`.
REAL_MAK_FIT = dict(
    C_c=3557.93,
    h_amb=0.5,
    T_amb=20.0,
    theta=116.55,
    n_delay=4,
    K_Q=9.8720,
    sigma=1.4e-9,
)

#: Literals, not the module's own reference temperatures: 550 F is `maxtemp`
#: and 75 F is `minstartuptemp`, both from common/settings_schema.py. Importing
#: the module's constants here would move every expectation below along with
#: any mutation of them, so the tests could never fail.
_HAZARD_C = (550.0 - 32.0) * 5.0 / 9.0
_FLOOR_C = (75.0 - 32.0) * 5.0 / 9.0


def _ev(candidate, incumbent=INCUMBENT, cand_rmse=2.0, inc_rmse=5.0, **kw):
    return evaluate(candidate, incumbent, candidate_rmse=cand_rmse, incumbent_rmse=inc_rmse, **{**HORIZON, **kw})


def _crossing_at(incumbent, t_cross_c, ratio):
    """A candidate whose effective tau equals `incumbent`'s at `t_cross_c`.

    Same sigma, C_c scaled by `ratio`, and h_amb solved so the two effective-tau
    curves meet exactly there. ratio < 1 puts the candidate above the incumbent
    below the crossing and below it above; ratio > 1 does the reverse. Which
    side of the crossing a reference temperature falls on is therefore what the
    verdict reports, which is what makes these pin the reference temperatures.
    """
    conductance = 4.0 * float(incumbent["sigma"]) * (t_cross_c + 273.15) ** 3
    h_amb = ratio * float(incumbent["h_amb"]) + (ratio - 1.0) * conductance
    return dict(incumbent, C_c=float(incumbent["C_c"]) * ratio, h_amb=h_amb)


def test_a_better_fit_is_accepted():
    assert _ev(GOOD).accepted is True


def test_a_worse_fit_is_refused():
    v = _ev(GOOD, cand_rmse=9.0, inc_rmse=5.0)
    assert v.accepted is False
    assert "rmse" in v.reason.lower()


def test_the_first_model_is_accepted_when_there_is_no_incumbent():
    assert _ev(GOOD, incumbent=None, inc_rmse=None).accepted is True


def test_a_parameter_outside_its_physical_range_is_refused():
    v = _ev(dict(GOOD, C_c=-5.0))
    assert v.accepted is False
    assert "C_c" in v.reason


def test_a_non_finite_parameter_is_refused():
    assert _ev(dict(GOOD, K_Q=float("nan"))).accepted is False


def test_a_non_integral_delay_count_is_refused():
    assert _ev(dict(GOOD, n_delay=4.5)).accepted is False


def test_a_non_finite_incumbent_rmse_is_refused_not_accepted():
    """A NaN incumbent RMSE must not fail open: every RMSE comparison against
    it is False, so without an explicit guard a huge-error, tau-shrinking
    candidate would sail through the refusal branch and be adopted."""
    faster = dict(GOOD, C_c=1000.0, h_amb=0.224)
    v = _ev(faster, cand_rmse=1e6, inc_rmse=float("nan"))
    assert v.accepted is False


def test_a_live_incumbent_with_unrecorded_rmse_is_refused():
    """A real incumbent whose RMSE was never recorded is not the same thing
    as no incumbent at all: the comparison cannot be made, so this must
    refuse rather than take the first-model acceptance path."""
    faster = dict(GOOD, C_c=1000.0, h_amb=0.224)
    v = _ev(faster, incumbent=INCUMBENT, cand_rmse=1e12, inc_rmse=None)
    assert v.accepted is False


def test_a_partial_incumbent_is_refused_not_a_crash():
    v = _ev(GOOD, incumbent={"C_c": 2000.0})
    assert v.accepted is False


def test_a_non_numeric_parameter_is_refused_not_a_crash():
    assert _ev(dict(GOOD, C_c="nine")).accepted is False


def test_a_negative_candidate_rmse_is_refused():
    """A negative RMSE is nonsense, and left unchecked it beats every
    incumbent automatically since it is less than any positive threshold."""
    faster = dict(GOOD, C_c=1000.0, h_amb=0.224)
    assert _ev(faster, cand_rmse=-1.0, inc_rmse=5.0).accepted is False


def test_a_zero_incumbent_rmse_is_refused():
    """A perfect incumbent cannot be fairly beaten. Pinned on the reason
    text, not just accepted=False: with candidate_rmse guaranteed positive
    by the earlier guard, the final RMSE-margin comparison alone would also
    refuse a positive candidate RMSE against a zero incumbent RMSE (any
    positive number beats a zero-or-negative threshold), so only the reason
    distinguishes this explicit guard from being deleted."""
    faster = dict(GOOD, C_c=1000.0, h_amb=0.224)
    v = _ev(faster, cand_rmse=0.001, inc_rmse=0.0)
    assert v.accepted is False
    assert "incumbent rmse" in v.reason.lower()


def test_a_non_numeric_delay_count_is_refused_not_a_crash():
    """n_delay="4.5" parses as finite (4.5) and passes the range check, then
    fails is_integer(); the refusal message must format the parsed number,
    not re-index the raw (still-a-string) candidate value."""
    assert _ev(dict(GOOD, n_delay="4.5")).accepted is False


def test_theta_zero_with_an_active_delay_chain_is_refused():
    """theta=0 with n_delay>=1 divides by zero building the transport-lag
    chain's per-stage time constant (theta/n_delay) in GreyBoxKF/GreyBoxEKF;
    a promoted model must be one the controller can actually run."""
    v = _ev(dict(GOOD, theta=0.0))  # n_delay stays 4: the chain is active
    assert v.accepted is False


def test_the_theta_bound_is_enforced():
    assert _ev(dict(GOOD, theta=-1e-9)).accepted is False
    assert _ev(dict(GOOD, theta=0.0, n_delay=0)).accepted is True
    assert _ev(dict(GOOD, theta=1200.0)).accepted is True
    assert _ev(dict(GOOD, theta=1200.0 + 1e-3)).accepted is False


def test_an_incumbent_missing_n_delay_is_refused_not_a_crash():
    incumbent = dict(C_c=2000.0, h_amb=0.30, theta=93.0, sigma=1.4e-9)  # n_delay omitted
    assert _ev(GOOD, incumbent=incumbent).accepted is False


def test_an_incumbent_missing_sigma_is_refused_not_a_crash():
    incumbent = dict(C_c=2000.0, h_amb=0.30, theta=93.0, n_delay=4)  # sigma omitted
    assert _ev(GOOD, incumbent=incumbent).accepted is False


def test_h_amb_alone_can_shrink_tau():
    """Raising h_amb alone (C_c unchanged) shortens tau exactly like cutting
    C_c does, so it must face the same wide margin -- pins h_amb's presence
    in the tau computation, not just C_c's."""
    faster = dict(GOOD, C_c=2000.0, h_amb=0.30 * 3)  # incumbent's own C_c, h_amb tripled
    v = _ev(faster, cand_rmse=4.85, inc_rmse=5.0)  # clears the 2% bar, not the 50% bar
    assert v.accepted is False


def test_n_delay_equal_to_one_keeps_the_delay_chain_active():
    """n_delay=1 is the smallest value that keeps the transport-delay chain
    on -- theta must still contribute, unlike n_delay=0."""
    one_delay = dict(GOOD, n_delay=1)
    v = _ev(one_delay, cand_rmse=4.85, inc_rmse=5.0)  # clears the 2% bar, not the 50% bar; theta unchanged
    assert v.accepted is True


def test_raising_sigma_needs_the_same_wide_margin_as_shortening_tau():
    """sigma prices into the effective tau via its linearized radiative
    conductance: raising it shortens the true braking distance even though C_c
    and h_amb are unchanged, and must face the same asymmetric bar."""
    incumbent = dict(GOOD, sigma=0.0)  # no radiative correction: effective tau == C_c/h_amb
    hotter_sigma = dict(GOOD, sigma=1e-8)  # at PROMOTION_BOUNDS' cap
    v = _ev(hotter_sigma, incumbent=incumbent, cand_rmse=4.85, inc_rmse=5.0)  # clears 2%, not 50%
    assert v.accepted is False


def test_raising_sigma_is_accepted_on_strong_evidence():
    incumbent = dict(GOOD, sigma=0.0)
    hotter_sigma = dict(GOOD, sigma=1e-8)
    assert _ev(hotter_sigma, incumbent=incumbent, cand_rmse=0.5, inc_rmse=5.0).accepted is True


def test_the_sigma_bound_is_enforced():
    assert _ev(dict(GOOD, sigma=-1e-12)).accepted is False
    assert _ev(dict(GOOD, sigma=0.0)).accepted is True
    assert _ev(dict(GOOD, sigma=1e-8)).accepted is True
    assert _ev(dict(GOOD, sigma=1e-8 + 1e-15)).accepted is False


def test_the_radiative_conductance_is_four_sigma_at_absolute_temperature():
    """The linearization of sigma*(T_c+273.15)**4 that GreyBoxEKF._discretize
    actually applies, pinned against literals: the factor 4 and the Kelvin
    offset both change how much braking distance a given sigma is charged
    for, and nothing else in this file can tell either of them apart from a
    different value."""
    params = dict(GOOD, C_c=2000.0, h_amb=0.30, sigma=1.4e-9)
    expected = 2000.0 / (0.30 + 4.0 * 1.4e-9 * (200.0 + 273.15) ** 3)
    assert effective_tau(params, 200.0) == pytest.approx(expected, rel=1e-12)


def test_trading_sigma_against_h_amb_cannot_launder_a_shortening_past_the_hot_end():
    """h_amb is flat in temperature while the radiative conductance grows as
    T**3, so a candidate can cut sigma and raise h_amb by amounts that leave
    the effective tau untouched at the hottest permitted temperature while
    genuinely shortening it everywhere below. Read at one temperature that is
    invisible; the whole operating range must be charged for."""
    incumbent = dict(GOOD, C_c=2000.0, h_amb=0.30, sigma=1.4e-9)
    cooler_sigma = 0.4e-9
    laundered = dict(
        incumbent,
        sigma=cooler_sigma,
        h_amb=0.30 + 4.0 * (1.4e-9 - cooler_sigma) * (_HAZARD_C + 273.15) ** 3,
    )
    assert effective_tau(laundered, _HAZARD_C) == pytest.approx(effective_tau(incumbent, _HAZARD_C), rel=1e-12)
    assert effective_tau(laundered, _FLOOR_C) < effective_tau(incumbent, _FLOOR_C)

    v = _ev(laundered, incumbent=incumbent, cand_rmse=4.85, inc_rmse=5.0)  # clears 2%, not 50%
    assert v.accepted is False
    assert "shorter tau" in v.reason.lower()


def test_the_laundered_shortening_is_still_accepted_on_strong_evidence():
    incumbent = dict(GOOD, C_c=2000.0, h_amb=0.30, sigma=1.4e-9)
    cooler_sigma = 0.4e-9
    laundered = dict(
        incumbent,
        sigma=cooler_sigma,
        h_amb=0.30 + 4.0 * (1.4e-9 - cooler_sigma) * (_HAZARD_C + 273.15) ** 3,
    )
    assert _ev(laundered, incumbent=incumbent, cand_rmse=0.5, inc_rmse=5.0).accepted is True


def test_repeated_sigma_for_h_amb_trades_cannot_walk_the_cool_end_tau_down():
    """The single-step trade compounds: each step is invisible at the hot end
    and small at the cool end, so on the narrow bar a chain of them deletes
    the modelled radiative loss outright and halves the true time constant at
    a low-and-slow hold."""
    incumbent, incumbent_rmse = dict(GOOD, C_c=2000.0, h_amb=0.30, sigma=1.4e-9), 5.0
    for _ in range(25):
        step = incumbent["sigma"] * 0.05
        candidate = dict(
            incumbent,
            sigma=incumbent["sigma"] - step,
            h_amb=incumbent["h_amb"] + 4.0 * step * (_HAZARD_C + 273.15) ** 3,
        )
        candidate_rmse = incumbent_rmse * 0.97  # clears the 2% bar decisively, not the 50% bar
        v = evaluate(candidate, incumbent, candidate_rmse=candidate_rmse, incumbent_rmse=incumbent_rmse, **HORIZON)
        if v.accepted:
            incumbent, incumbent_rmse = candidate, candidate_rmse
    assert incumbent["sigma"] == GOOD["sigma"]
    assert incumbent["h_amb"] == 0.30


def test_a_crossing_above_the_hot_end_leaves_the_candidate_longer_throughout():
    """Pins the hot reference from above. The two effective-tau curves meet
    half a degree past the hard shutoff, so the candidate is the slower model
    everywhere the grill may actually run and the narrow bar applies. A
    reference read any hotter than the crossing would see a shortening that
    the grill can never reach."""
    candidate = _crossing_at(INCUMBENT, _HAZARD_C + 0.5, ratio=0.9)
    assert _ev(candidate, cand_rmse=4.85, inc_rmse=5.0).accepted is True


def test_a_crossing_below_the_hot_end_is_charged_the_wide_bar():
    """Pins the hot reference from below. The curves meet half a degree under
    the hard shutoff, so the candidate is quicker at the top of the range and
    slower everywhere else -- invisible to any reference read cooler than the
    crossing."""
    candidate = _crossing_at(INCUMBENT, _HAZARD_C - 0.5, ratio=0.9)
    assert _ev(candidate, cand_rmse=4.85, inc_rmse=5.0).accepted is False


def test_a_crossing_below_the_cool_end_leaves_the_candidate_longer_throughout():
    """Pins the cool reference from below. The curves meet half a degree under
    the flameout floor, so the candidate is the slower model throughout the
    range the controller drives, and the narrow bar applies."""
    candidate = _crossing_at(INCUMBENT, _FLOOR_C - 0.5, ratio=1.1)
    assert _ev(candidate, cand_rmse=4.85, inc_rmse=5.0).accepted is True


def test_a_crossing_above_the_cool_end_is_charged_the_wide_bar():
    """Pins the cool reference from above. The curves meet half a degree over
    the flameout floor, so the candidate is quicker at the bottom of the range
    and slower everywhere else -- invisible to any reference read hotter than
    the crossing."""
    candidate = _crossing_at(INCUMBENT, _FLOOR_C + 0.5, ratio=1.1)
    assert _ev(candidate, cand_rmse=4.85, inc_rmse=5.0).accepted is False


def test_repeated_small_sigma_increases_cannot_walk_true_tau_down_without_clearing_the_wide_bar():
    """sigma raises the effective tau's radiative conductance the same way a
    C_c/h_amb cut lowers it directly; a chain of small sigma increases must
    face the same wide margin as any other tau-shrinking route."""
    incumbent, incumbent_rmse = dict(GOOD, sigma=0.0), 5.0
    for _ in range(15):
        candidate = dict(incumbent, sigma=incumbent["sigma"] + 1e-10)  # small step toward the 2e-9 cap
        candidate_rmse = incumbent_rmse * 0.97  # clears the 2% bar decisively, not the 50% bar
        v = evaluate(candidate, incumbent, candidate_rmse=candidate_rmse, incumbent_rmse=incumbent_rmse, **HORIZON)
        if v.accepted:
            incumbent, incumbent_rmse = candidate, candidate_rmse
    assert incumbent["sigma"] == 0.0


def test_repeated_joint_sigma_and_tau_cuts_cannot_walk_true_tau_down_without_clearing_the_wide_bar():
    """A candidate can cut C_c and raise sigma in the same promotion; the
    guard must catch the combined effect on true tau, not just each
    parameter considered alone."""
    incumbent, incumbent_rmse = dict(GOOD, sigma=0.0), 5.0
    for _ in range(15):
        candidate = dict(
            incumbent,
            C_c=incumbent["C_c"] * 0.97,  # small cut, well under the old 10% deadband
            sigma=incumbent["sigma"] + 5e-11,  # small step, well under the 2e-9 cap
        )
        candidate_rmse = incumbent_rmse * 0.97  # clears the 2% bar decisively, not the 50% bar
        v = evaluate(candidate, incumbent, candidate_rmse=candidate_rmse, incumbent_rmse=incumbent_rmse, **HORIZON)
        if v.accepted:
            incumbent, incumbent_rmse = candidate, candidate_rmse
    assert incumbent["C_c"] == GOOD["C_c"]
    assert incumbent["sigma"] == 0.0


def test_an_incumbent_with_no_positive_reference_always_faces_the_wide_margin():
    """A zero effective dead time on the incumbent side cannot be safely
    divided into or compared against, so it is treated as the risky case
    rather than silently taking the narrow bar."""
    incumbent = dict(GOOD, C_c=2000.0, h_amb=0.30, theta=0.0, n_delay=0)
    v = _ev(GOOD, incumbent=incumbent, cand_rmse=4.85, inc_rmse=5.0)  # clears the 2% bar, not the 50% bar
    assert v.accepted is False


def test_a_zero_time_step_is_refused_not_a_crash():
    assert _ev(GOOD, n_horizon=144, t_step=0.0).accepted is False


def test_a_non_finite_time_step_does_not_report_the_horizon_as_adequate():
    v = _ev(GOOD, n_horizon=144, t_step=float("nan"))
    assert v.accepted is False


def test_a_negative_horizon_count_is_refused():
    assert _ev(GOOD, n_horizon=-1, t_step=25.0).accepted is False


def test_shrinking_tau_needs_more_evidence_than_raising_it():
    """The asymmetry is the safety argument. Believing the grill is more
    sluggish than it is makes the controller brake early and costs nothing;
    believing it is less sluggish is the 520 F incident."""
    slower = dict(GOOD, C_c=4000.0, h_amb=0.224)  # tau up
    faster = dict(GOOD, C_c=1000.0, h_amb=0.224)  # tau down
    margin = dict(cand_rmse=4.85, inc_rmse=5.0)  # clears the 2% bar, not the 50% bar
    assert _ev(slower, **margin).accepted is True
    assert _ev(faster, **margin).accepted is False


def test_a_large_tau_reduction_is_accepted_on_strong_evidence():
    faster = dict(GOOD, C_c=1000.0, h_amb=0.224)
    assert _ev(faster, cand_rmse=0.5, inc_rmse=5.0).accepted is True


def test_repeated_small_tau_cuts_cannot_walk_tau_down_without_clearing_the_wide_bar():
    """A chain of cuts just under the old 10% deadband, each individually
    plausible on the narrow margin, must never compound into a large,
    unproven tau reduction: every one of them must face the wide margin
    instead, or the incumbent never advances."""
    incumbent, incumbent_rmse = dict(GOOD), 5.0
    for _ in range(15):
        candidate = dict(incumbent, C_c=incumbent["C_c"] * 0.91)  # ~9% cut, just under the old deadband
        candidate_rmse = incumbent_rmse * 0.97  # clears the 2% bar decisively, not the 50% bar
        v = evaluate(candidate, incumbent, candidate_rmse=candidate_rmse, incumbent_rmse=incumbent_rmse, **HORIZON)
        if v.accepted:
            incumbent, incumbent_rmse = candidate, candidate_rmse
    assert incumbent["C_c"] == GOOD["C_c"]


def test_setting_n_delay_to_zero_needs_the_same_wide_margin_as_shortening_theta():
    """n_delay=0 removes the transport-lag chain outright, so it cuts the
    effective dead time to zero even if theta itself is untouched. That must
    face the same asymmetric bar as shortening theta directly, not the
    narrow one theta's own unchanged value would otherwise suggest."""
    no_delay = dict(GOOD, n_delay=0)
    v = _ev(no_delay, cand_rmse=4.85, inc_rmse=5.0)  # clears the 2% bar, not the 50% bar
    assert v.accepted is False


def test_setting_n_delay_to_zero_is_accepted_on_strong_evidence():
    no_delay = dict(GOOD, n_delay=0)
    assert _ev(no_delay, cand_rmse=0.5, inc_rmse=5.0).accepted is True


def test_the_n_delay_bound_is_enforced():
    assert _ev(dict(GOOD, n_delay=-1e-9)).accepted is False
    assert _ev(dict(GOOD, n_delay=50.0)).accepted is True
    assert _ev(dict(GOOD, n_delay=50.0 + 1e-6)).accepted is False


def test_the_rmse_margin_is_exactly_two_percent():
    """Pinned against a literal, not the module's own constant: importing
    _RMSE_MARGIN here would move this test's threshold with any mutation of
    it, so the test could never fail no matter what the constant became."""
    slower = dict(GOOD, C_c=4000.0, h_amb=0.224)  # longer tau: the narrow margin applies
    at_margin = _ev(slower, cand_rmse=4.9, inc_rmse=5.0)  # 5.0 * (1 - 0.02)
    just_worse = _ev(slower, cand_rmse=4.92, inc_rmse=5.0)
    assert at_margin.accepted is True
    assert just_worse.accepted is False


def test_the_faster_rmse_margin_is_exactly_fifty_percent():
    """Pinned against a literal for the same reason as the test above."""
    faster = dict(GOOD, C_c=1000.0, h_amb=0.224)  # shorter tau: the wide margin applies
    at_margin = _ev(faster, cand_rmse=2.5, inc_rmse=5.0)  # 5.0 * (1 - 0.50)
    just_worse = _ev(faster, cand_rmse=2.52, inc_rmse=5.0)
    assert at_margin.accepted is True
    assert just_worse.accepted is False


def test_a_small_tau_increase_is_reported_as_unchanged_not_longer():
    """theta is held equal to the incumbent so its own "unchanged" label
    cannot make this pass regardless of tau's label -- the assertion checks
    the tau phrase specifically."""
    within_deadband = dict(GOOD, C_c=2000.0 * 1.05, h_amb=0.30)  # +5% tau: inside the 10% deadband
    v = _ev(within_deadband, cand_rmse=9.0, inc_rmse=5.0)  # deliberately refused; inspect the label
    assert v.accepted is False
    assert "unchanged tau" in v.reason.lower()


def test_a_material_tau_increase_is_reported_as_longer():
    beyond_deadband = dict(GOOD, C_c=2000.0 * 1.20, h_amb=0.30)  # +20% tau: past the 10% deadband
    v = _ev(beyond_deadband, cand_rmse=9.0, inc_rmse=5.0)
    assert v.accepted is False
    assert "longer tau" in v.reason.lower()


def test_shortening_dead_time_needs_the_same_wide_margin_as_tau():
    """theta shortening under-anticipates the transport delay the same way a
    short tau under-anticipates the chamber lag: both make the controller
    over-feed. It must face the same asymmetric bar."""
    shorter_theta = dict(GOOD, theta=10.0)
    v = _ev(shorter_theta, cand_rmse=4.85, inc_rmse=5.0)  # clears the 2% bar, not the 50% bar
    assert v.accepted is False


def test_a_model_needing_more_horizon_than_configured_reports_it():
    """A braking distance of a few hundred seconds against a 2*25 = 50 s horizon.

    50 s is genuinely short for this model: GOOD's chamber goes on rising for
    321 s after a fuel cut. The horizon has to be this small for the test to
    bite, because 600 s -- what the grill ships with -- already covers GOOD
    twice over.
    """
    v = _ev(GOOD, n_horizon=2, t_step=25.0)
    assert v.horizon_needed is not None
    assert v.horizon_needed > 2


def test_an_adequate_horizon_asks_for_nothing():
    assert _ev(GOOD, n_horizon=600, t_step=25.0).horizon_needed is None


def test_the_horizon_is_sized_from_the_braking_distance_not_from_the_time_constant():
    """What the horizon has to cover is the coast after a fuel cut.

    The demand used to be C_c/h_amb over t_step. It is not any more, and these
    two models say so: they carry the same C_c/h_amb -- so the old rule would
    ask for the same 160 steps from both -- while their transport delays, and
    so the distances they take to stop, differ by a factor of four.

    Pinned as a ratio rather than a step count because what changed is which
    quantity is being read, not the arithmetic that turns seconds into steps.
    """
    slow_chain = dict(GOOD, C_c=2000.0, h_amb=0.5, theta=400.0)
    fast_chain = dict(GOOD, C_c=2000.0, h_amb=0.5, theta=100.0)
    assert slow_chain["C_c"] / slow_chain["h_amb"] == fast_chain["C_c"] / fast_chain["h_amb"]

    ratio = longest_braking_distance(slow_chain) / longest_braking_distance(fast_chain)
    assert ratio == pytest.approx(4.0, rel=0.05)

    slow = _ev(slow_chain, n_horizon=1, t_step=25.0).horizon_needed
    fast = _ev(fast_chain, n_horizon=1, t_step=25.0).horizon_needed
    assert slow > fast
    # The old rule's answer, 4000 s over a 25 s step, must not be either of them.
    assert 160 not in (slow, fast)


def test_a_model_that_cannot_hold_the_reference_temperature_has_nothing_to_brake():
    """Full fire below the chamber's own loss means the chamber is not rising.

    This is the boundary the estimate is built on -- the crossing it looks for
    is where the decaying flux meets the loss -- so a model already on the far
    side of it has a braking distance of zero and asks for no horizon at all.
    """
    feeble = dict(GOOD, K_Q=1e-3, h_amb=1e3)
    assert braking_distance(feeble, _HAZARD_C) == 0.0
    assert _ev(feeble, n_horizon=1, t_step=25.0).horizon_needed is None


def test_a_chamber_with_no_delay_chain_has_nothing_to_brake():
    """n_delay 0 leaves no stage at all, so there is nothing left in flight.

    The transport chain was the second of two cascades; the firepot was the
    other, and dropping it is what this model no longer has. So with n_delay 0
    the fuel cut removes the entire heat input at that instant and the chamber
    starts losing immediately. Zero is the model's own answer, not a guard
    falling through: `braking_distance` reaches it only after clearing the
    checks that report infinity, which the assertions below pin by showing the
    same parameters still demand a real distance once one lag state exists.
    """
    no_chain = dict(GOOD, n_delay=0)
    assert braking_distance(no_chain, _HAZARD_C) == 0.0
    assert _ev(no_chain, n_horizon=1, t_step=25.0).horizon_needed is None
    # Same model, one lag state: the chain is back and so is the demand, so the
    # zero above is the absent chain and not an unreachable code path.
    assert braking_distance(dict(no_chain, n_delay=1), _HAZARD_C) > 0.0


def test_one_lag_state_brakes_on_the_closed_form_a_single_lag_has():
    """With one stage the Erlang chain is a plain exponential.

    That has a closed form the implementation can be checked against rather
    than restated: a single charged lag of mean `theta` reaches the chamber's
    loss after theta * ln(flux/loss). Written out here so it pins the
    implementation instead of importing it.
    """
    one = dict(GOOD, n_delay=1)
    loss = one["h_amb"] * (_HAZARD_C - one["T_amb"]) + one["sigma"] * (
        (_HAZARD_C + 273.15) ** 4 - (one["T_amb"] + 273.15) ** 4
    )
    expected = one["theta"] * math.log(one["K_Q"] * 100.0 / loss)
    assert expected > 0.0
    assert braking_distance(one, _HAZARD_C) == pytest.approx(expected, rel=1e-9)


def test_the_chain_is_the_transport_delay_and_nothing_longer():
    """Every stage is theta/n_delay, so the chain's mean is theta itself.

    The estimate used to pad the cascade -- n_delay+1 stages read at the
    slowest of two unequal lengths -- because the firepot's stage and a
    transport stage were not the same size. With one lump they are all the same
    size, so the padding is gone and the answer is the model's own decay. An
    implementation that still scaled the mean by an extra stage would read
    longer than this at every n_delay, so the check is that raising n_delay at
    a fixed theta leaves the chain sharper, not longer.
    """
    at = {n: braking_distance(dict(GOOD, n_delay=n), _HAZARD_C) for n in (1, 2, 4, 8)}
    # More stages of the same total mean is a sharper, more plug-flow delay:
    # the flux is held up longer before it starts falling but then falls
    # faster, and the crossing this looks for is late in that fall.
    assert at[8] < at[4] < at[2] < at[1]
    # A pure Erlang of mean theta can never outlast the single exponential of
    # the same mean by more than that exponential's own crossing.
    assert at[1] == pytest.approx(
        GOOD["theta"]
        * math.log(
            GOOD["K_Q"]
            * 100.0
            / (
                GOOD["h_amb"] * (_HAZARD_C - GOOD["T_amb"])
                + GOOD["sigma"] * ((_HAZARD_C + 273.15) ** 4 - (GOOD["T_amb"] + 273.15) ** 4)
            )
        ),
        rel=1e-9,
    )


def test_the_radiative_loss_shortens_the_braking_distance():
    """Radiation is most of a hot chamber's loss, so it is most of its brake.

    The flux has to fall to the loss for the chamber to stop, so a model that
    left the radiative term out of that loss would have the flux fall further
    and would report a longer coast than the model actually has. Checked at
    both ends of the range, because the term is negligible at one of them and
    dominant at the other, and a check at the cool end alone would barely move.
    """
    linear_only = dict(GOOD, sigma=0.0)
    assert braking_distance(linear_only, _HAZARD_C) > braking_distance(GOOD, _HAZARD_C)
    assert braking_distance(linear_only, _FLOOR_C) > braking_distance(GOOD, _FLOOR_C)
    # And it is the hot end where dropping it matters most.
    hot = braking_distance(linear_only, _HAZARD_C) / braking_distance(GOOD, _HAZARD_C)
    cool = braking_distance(linear_only, _FLOOR_C) / braking_distance(GOOD, _FLOOR_C)
    assert hot > cool


def test_the_implied_steady_state_is_where_full_fire_meets_the_chamber_loss():
    """The asymptote a cook that never gets there cannot determine.

    Asserted against the balance it solves rather than a number, so it pins the
    definition; and it must rise with the fire and fall with the losses, which
    is what makes an absurd value the sign of a fit that traded those against
    each other along a direction its log could not see.
    """
    t_ss = steady_state_at_full_fire(GOOD)
    loss = GOOD["h_amb"] * (t_ss - GOOD["T_amb"]) + GOOD["sigma"] * (
        (t_ss + 273.15) ** 4 - (GOOD["T_amb"] + 273.15) ** 4
    )
    assert loss == pytest.approx(GOOD["K_Q"] * 100.0, rel=1e-9)
    assert steady_state_at_full_fire(dict(GOOD, K_Q=GOOD["K_Q"] * 4)) > t_ss
    assert steady_state_at_full_fire(dict(GOOD, h_amb=GOOD["h_amb"] * 4)) < t_ss
    # The escape this exists to expose. Both this task and the parallel
    # parsimony study fitted the real cook with the old five-parameter free
    # set and landed at C_c 1.06e5 with C_c/h_amb 3552 -- an asymptote of
    # 1713 F on a grill that peaked at 520 F. The sound fit says 1067 F.
    escaped = dict(REAL_MAK_FIT, C_c=1.06e5, h_amb=1.06e5 / 3552.0, K_Q=302.4)
    assert steady_state_at_full_fire(escaped) * 9.0 / 5.0 + 32.0 == pytest.approx(1713.0, abs=2.0)
    assert steady_state_at_full_fire(REAL_MAK_FIT) * 9.0 / 5.0 + 32.0 == pytest.approx(1065.0, abs=2.0)
    # 1.6x apart, and both far above the 550 F hazard limit -- which is why
    # this is reported and not turned into a refusal. A line drawn between two
    # values that close would be a guess, and `evaluate` does not see the
    # temperature band the cook actually visited, which is what would separate
    # them properly.
    assert steady_state_at_full_fire(escaped) / steady_state_at_full_fire(REAL_MAK_FIT) < 2.0
    assert min(steady_state_at_full_fire(escaped), steady_state_at_full_fire(REAL_MAK_FIT)) > _HAZARD_C


def test_the_braking_distance_is_read_at_the_end_of_the_range_that_takes_longest():
    """One horizon has to be adequate everywhere the grill runs.

    The cool end is where the flux has furthest to fall before it meets the
    chamber's loss, so it is the end that sizes the horizon. Reading the hot
    end instead would ask for less than the grill needs at the cool one.
    """
    cool = braking_distance(GOOD, _FLOOR_C)
    hot = braking_distance(GOOD, _HAZARD_C)
    assert cool > hot
    assert longest_braking_distance(GOOD) == cool


def test_a_reference_at_or_below_ambient_is_not_read_as_an_endless_brake():
    """Nothing pulls heat out of a chamber the surroundings are warming.

    The cool end of the operating range is 23.9 C, so a warm day puts it under
    ambient, where the loss term goes negative and the chamber never stops
    rising on its own. That is not a braking distance and must not become an
    infinite horizon demand: the hot end is above any ambient the bounds
    admit, so it is the one that answers.
    """
    warm_day = dict(GOOD, T_amb=35.0)
    assert braking_distance(warm_day, _FLOOR_C) == math.inf
    assert math.isfinite(longest_braking_distance(warm_day))
    assert longest_braking_distance(warm_day) == braking_distance(warm_day, _HAZARD_C)


def test_the_estimate_matches_the_coast_the_real_cook_shows_at_the_cook_s_own_temperature():
    """Like for like: same temperature, and a step compared against a step.

    The 450 F cook in tests/unit/mpc/fixtures/mak_cook_2026-08-02.csv peaked at
    271.3 C, so the estimate is read there and nowhere else -- the braking
    distance is a function of chamber temperature, and comparing a reading at
    one temperature against a coast measured at another says nothing about
    either.

    The cook's own coast also has to be reduced to a step before it can be
    compared to one. The controller did not cut fuel; it tapered Q from 100
    down to 5 over the 263 s to the peak, and `braking_distance` asks what a
    cut does. The equal-area equivalent step -- the instant at which a single
    step delivers the same heat as the taper did -- is 968 s, so the step-
    equivalent coast is 140 s, not the 263 s the raw timestamps give.

    Against that, the estimate is 151 s: longer than the grill's, which is the
    direction the remaining approximation in `braking_distance` -- a chamber
    held at its starting temperature through the coast, where a warming one
    loses more -- is argued to err.

    The margin used to be wider. The two-lump model read 173 s here, and most
    of that extra was padding rather than physics: the estimate read n_delay+1
    stages at the slower of the firepot's stage and a transport stage, a chain
    of longer total mean than the model actually had. With one lump every stage
    is the same length and the Erlang is the model's own decay, so what is left
    over the grill's 140 s is 8% rather than 24%. That is a real reduction in
    how far this over-states, and it is deliberate -- an estimate is not made
    safer by being wrong in a comfortable direction -- but it is why the
    horizon is sized at the cool end, where the demand is twice this one.
    """
    # From the fixture: Q leaves 100 at t=846 s, reaches its floor of 5 at
    # t=1119 s, and the chamber peaks at 271.278 C at t=1109 s. The equal-area
    # equivalent step of that taper falls at t=968 s.
    peak_temp_c, peak_t_s, equivalent_step_t_s = 271.278, 1108.573, 968.2
    step_equivalent_coast_s = peak_t_s - equivalent_step_t_s
    assert step_equivalent_coast_s == pytest.approx(140.0, abs=1.0)

    estimate = braking_distance(REAL_MAK_FIT, peak_temp_c)
    assert estimate == pytest.approx(151.0, abs=1.0)
    assert 1.0 < estimate / step_equivalent_coast_s < 1.25

    # Read at the wrong temperature the same model says something else
    # entirely, which is why this test fixes the temperature.
    assert braking_distance(REAL_MAK_FIT, _FLOOR_C) > 2.0 * estimate


def test_the_real_cook_needs_a_horizon_in_the_order_the_cook_itself_shows():
    """The defect that shipped: a demand two orders of magnitude past the cook.

    `horizon_needed` is sized from the cool end of the operating range, not
    from the temperature the cook happened to reach, because one horizon has
    to be adequate everywhere the grill runs. That reading is 346 s -- longer
    than the 151 s the cook's own temperature calls for, and still the same
    order as the 263 s the log spans between fuel cut and peak.

    Sized from C_c/h_amb the demand was 7137 s, 286 steps: a horizon the log
    contains no evidence for, since a ramp that never approaches steady state
    does not determine that ratio.
    """
    raw_coast_s = 1108.573 - 845.966
    assert raw_coast_s == pytest.approx(263.0, abs=1.0)

    brake = longest_braking_distance(REAL_MAK_FIT)
    assert brake == pytest.approx(346.0, abs=2.0)
    assert brake < 2.0 * raw_coast_s

    v = _ev(REAL_MAK_FIT, n_horizon=1, t_step=25.0)
    assert v.horizon_needed == int(math.ceil(brake / 25.0))
    # The old rule, for contrast: C_c/h_amb over the same 25 s step.
    assert REAL_MAK_FIT["C_c"] / REAL_MAK_FIT["h_amb"] / 25.0 > 10 * v.horizon_needed
    # And the horizon the grill actually shipped with covers it, which is why
    # this incident was never the horizon's fault.
    assert _ev(REAL_MAK_FIT, n_horizon=24, t_step=25.0).horizon_needed is None


def test_a_model_that_never_stops_rising_is_refused_rather_than_passed_quietly(monkeypatch):
    """An unbounded brake must not read as "the horizon is fine".

    `braking_distance` returns infinity for a chamber nothing pulls heat out
    of. PROMOTION_BOUNDS makes that unreachable through `evaluate` today --
    h_amb and K_Q both have positive floors, and the reference points at
    or below ambient are dropped before they can produce a non-positive loss --
    so this reaches past the bounds to force the branch rather than pretending
    a candidate can express it. The branch exists because `horizon_needed`
    is advisory: leaving it None on a model with no finite braking distance
    would let the worst case be the one that travels silently.
    """
    import controller.model_promotion as mp

    monkeypatch.setattr(mp, "longest_braking_distance", lambda *a, **k: math.inf)
    verdict = _ev(GOOD, n_horizon=24, t_step=25.0)
    assert verdict.accepted is False
    assert verdict.horizon_needed is None
    assert "stops rising" in verdict.reason


def test_holding_h_amb_narrows_the_believed_tau_far_more_than_the_braking_distance():
    """What the fitter's held h_amb costs, in both directions.

    controller/update_mpc.py holds h_amb, so a grill whose true ambient loss is
    not the held value is described by a model carrying the right C_c/h_amb and
    K_Q/h_amb and the wrong split between conductive and radiative loss. The
    believed time constant is exposed to that in both directions: across a 50x
    sweep of the true h_amb it reads anywhere from 0.40x to 3.66x the truth's.

    The narrowing half is the one that matters. A believed tau shorter than the
    truth is a model that thinks the grill stops sooner than it does, which is
    the failure this whole policy exists to prevent -- and controller/grill_sim
    sits on that side of nominal. The braking distance is far less exposed
    there: 0.85x against tau's 0.40x, and the range-wide reading the horizon is
    actually sized from holds to 0.98x, because it is taken at the cool end
    where the radiative share the hold gets wrong is small.
    """
    believed = dict(REAL_MAK_FIT)
    tau_ratios, brake_ratios, sizing_ratios = [], [], []
    for mult in (0.2, 0.5, 1.0, 2.0, 5.0, 10.0):
        # The same log, read as a grill with `mult` times the ambient loss: the
        # ratios a cook determines are held, the absolute values are not.
        truth = dict(
            believed,
            h_amb=believed["h_amb"] * mult,
            C_c=believed["C_c"] * mult,
            K_Q=believed["K_Q"] * mult,
        )
        for t_ref in (_FLOOR_C, _HAZARD_C):
            tau_ratios.append(effective_tau(believed, t_ref) / effective_tau(truth, t_ref))
            brake_ratios.append(braking_distance(believed, t_ref) / braking_distance(truth, t_ref))
        sizing_ratios.append(longest_braking_distance(believed) / longest_braking_distance(truth))

    # The exposure is real and it is stated, not claimed away.
    assert min(tau_ratios) < 0.45
    assert max(tau_ratios) > 3.0
    # The braking distance narrows too, but by half as much on a log scale...
    assert 0.80 < min(brake_ratios) < 0.90
    assert min(brake_ratios) > 2.0 * min(tau_ratios)
    # ...and the reading the horizon is sized from barely narrows at all.
    assert min(sizing_ratios) > 0.95


def test_every_fitted_parameter_has_a_bound():
    for key in GOOD:
        assert key in PROMOTION_BOUNDS


#: Literal, not derived from PROMOTION_BOUNDS: reading the bounds under test
#: from the dict they are meant to pin would move the expected edge along
#: with any mutation of it, so the test could never fail no matter what the
#: bound became.
_EXPECTED_BOUNDS = {
    "C_c": (1.0, 1e6),
    "h_amb": (1e-4, 1e3),
    "T_amb": (-40.0, 60.0),
    "theta": (0.0, 1200.0),
    "n_delay": (0.0, 50.0),
    "K_Q": (1e-3, 1e4),
    "sigma": (0.0, 1e-8),
}


def test_every_bound_is_pinned_by_a_literal():
    assert _EXPECTED_BOUNDS == PROMOTION_BOUNDS


#: n_delay and theta are covered by their own dedicated tests instead: n_delay's
#: lower edge (0) interacts with theta through the effective-dead-time rule, and
#: theta's lower edge (0) is only valid when n_delay is also 0 (otherwise the
#: transport-delay chain divides by n_delay into a zero theta) -- both depend on
#: the OTHER parameter's value, not just on whether the bare value is in range.
@pytest.mark.parametrize(
    "key,lo,hi", [(k, *bounds) for k, bounds in _EXPECTED_BOUNDS.items() if k not in ("n_delay", "theta")]
)
def test_each_bound_is_enforced_at_its_edge(key, lo, hi):
    assert _ev(dict(GOOD, **{key: lo})).accepted is True
    assert _ev(dict(GOOD, **{key: lo - abs(lo) * 1e-6 - 1e-9})).accepted is False

    assert _ev(dict(GOOD, **{key: hi})).accepted is True
    assert _ev(dict(GOOD, **{key: hi + abs(hi) * 1e-6 + 1e-9})).accepted is False
