[program:display]
command=/usr/local/bin/pifire/bin/python /usr/local/bin/pifire/display_launch.py
directory=/usr/local/bin/pifire
autostart=true
autorestart=true
startretries=3
stopasgroup=true
stderr_logfile=/usr/local/bin/pifire/logs/display.err.log
stdout_logfile=/usr/local/bin/pifire/logs/display.out.log
