import type { HistoryChartData } from "../src/contracts/content.gen";
import { describe, expect, it } from "@rstest/core";
import { hasPlottableHistory, toChartInput } from "../src/history/historyAdapter";

// Mirrors a real prepare_chartdata result (generated by calling the Python
// function with a seeded history): every point's `x` equals the matching
// `time_labels` entry, targets/setpoints are separate datasets, and a probe
// disabled in Settings comes back with `hidden: true`.
const POPULATED: HistoryChartData = {
  time_labels: [1784942370612, 1784942373612, 1784942376612],
  chart_data: [
    {
      label: "Grill",
      borderColor: "rgb(0, 64, 255, 1)",
      hidden: false,
      data: [
        { x: 1784942370612, y: 100 },
        { x: 1784942373612, y: 110 },
        { x: 1784942376612, y: 120 },
      ],
    },
    {
      label: "Grill Target",
      borderColor: "rgb(0, 128, 255, 1)",
      hidden: false,
      data: [
        { x: 1784942370612, y: 225 },
        { x: 1784942373612, y: 225 },
        { x: 1784942376612, y: 225 },
      ],
    },
    {
      label: "Probe 1",
      borderColor: "#888",
      hidden: true,
      data: [
        { x: 1784942370612, y: 90 },
        { x: 1784942373612, y: 95 },
        { x: 1784942376612, y: 100 },
      ],
    },
  ],
  probe_mapper: { probes: { grill1: 0 }, targets: { grill1: 1 }, primarysp: {} },
  graph_labels: { probes: { grill1: "Grill" }, targets: { grill1: "Grill Target" }, primarysp: {} },
  annotations: {},
  minutes: 60,
};

const EMPTY: HistoryChartData = {
  time_labels: [],
  chart_data: [
    { label: "Grill", borderColor: "rgb(0, 64, 255, 1)", hidden: false, data: [] },
    { label: "Grill Target", borderColor: "rgb(0, 128, 255, 1)", hidden: false, data: [] },
  ],
  probe_mapper: { probes: { grill1: 0 }, targets: { grill1: 1 }, primarysp: {} },
  graph_labels: { probes: { grill1: "Grill" }, targets: { grill1: "Grill Target" }, primarysp: {} },
  annotations: {},
  minutes: 60,
};

describe("toChartInput", () => {
  it("converts epoch milliseconds to the epoch SECONDS the chart expects", () => {
    // The single most consequential line in this module: web's uPlot tooltip
    // does `new Date(x * 1000)`, so passing the API's milliseconds through
    // unchanged dates every sample ~50,000 years into the future while the
    // chart still draws a plausible-looking line.
    const { times } = toChartInput(POPULATED);

    expect(times).toEqual([1784942370.612, 1784942373.612, 1784942376.612]);
    expect(new Date(times[0] * 1000).toISOString()).toBe("2026-07-25T01:19:30.612Z");
    // What passing the raw milliseconds through would have produced:
    expect(new Date(POPULATED.time_labels[0] * 1000).getUTCFullYear()).toBeGreaterThan(50000);
  });

  it("maps each dataset's y values in time order", () => {
    const { series } = toChartInput(POPULATED);

    expect(series.map((s) => s.label)).toEqual(["Grill", "Grill Target", "Probe 1"]);
    expect(series[0].values).toEqual([100, 110, 120]);
    expect(series[1].values).toEqual([225, 225, 225]);
    expect(series[2].values).toEqual([90, 95, 100]);
  });

  it("carries each dataset's borderColor through as the series stroke", () => {
    expect(toChartInput(POPULATED).series[0].color).toBe("rgb(0, 64, 255, 1)");
  });

  it("falls back to a readable stroke when a dataset has no borderColor", () => {
    const noColor: HistoryChartData = {
      ...POPULATED,
      chart_data: [{ label: "Grill", data: POPULATED.chart_data[0].data }],
    };

    // Theme.dim / --text-dim on web. web-react/tests/unit/themeTokens.test.ts
    // is what keeps this literal and the token in step; this test only pins
    // that the fallback is used.
    expect(toChartInput(noColor).series[0].color).toBe("#8a7f70");
  });

  it("keeps a hidden dataset, marked not visible rather than dropped", () => {
    // `hidden` means "off", not "discard". It used to mean discard, and the
    // consequence was that a probe switched off in Settings had its recorded
    // history silently thrown away here -- nothing drew it and nothing said it
    // existed. The chart's own controls decide what is drawn now.
    const { series } = toChartInput(POPULATED);

    const probe = series.find((s) => s.label === "Probe 1");
    expect(probe).toBeDefined();
    expect(probe?.visible).toBe(false);
    expect(probe?.values).toEqual([90, 95, 100]);
  });

  it("marks datasets the server did not hide as visible", () => {
    const { series } = toChartInput(POPULATED);

    expect(series.find((s) => s.label === "Grill")?.visible).toBe(true);
  });

  it("carries the axis a series belongs to", () => {
    const withDuty: HistoryChartData = {
      ...POPULATED,
      chart_data: [
        { label: "Grill", borderColor: "#f00", hidden: false, axis: "temp", data: [] },
        { label: "Auger Duty", borderColor: "#ff8a2b", hidden: true, axis: "duty", data: [] },
      ],
    };

    const { series } = toChartInput(withDuty);

    expect(series.map((s) => s.axis)).toEqual(["temp", "duty"]);
  });

  it("treats a dataset with no axis as a temperature", () => {
    // A cook file written before duty existed carries no `axis` on its
    // datasets, and every series in one is a temperature. Defaulting the other
    // way would plot an old cook's probes against a 0-100% scale.
    const { series } = toChartInput(POPULATED);

    expect(series.every((s) => s.axis === "temp")).toBe(true);
  });

  it("pads a dataset shorter than time_labels with nulls so the chart stays aligned", () => {
    const ragged: HistoryChartData = {
      ...POPULATED,
      chart_data: [{ label: "Grill", data: [{ x: 1784942370612, y: 100 }] }],
    };

    const { times, series } = toChartInput(ragged);

    expect(series[0].values).toEqual([100, null, null]);
    expect(series[0].values.length).toBe(times.length);
  });

  it("keeps a null reading as a gap rather than turning it into zero", () => {
    const withGap: HistoryChartData = {
      ...POPULATED,
      chart_data: [
        {
          label: "Grill",
          data: [
            { x: 1784942370612, y: 100 },
            { x: 1784942373612, y: null },
            { x: 1784942376612, y: 120 },
          ],
        },
      ],
    };

    expect(toChartInput(withGap).series[0].values).toEqual([100, null, 120]);
  });

  it("returns empty arrays for an empty history instead of throwing", () => {
    const { times, series } = toChartInput(EMPTY);

    expect(times).toEqual([]);
    expect(series.map((s) => s.values)).toEqual([[], []]);
  });
});

describe("hasPlottableHistory", () => {
  it("is true for a payload with samples", () => {
    expect(hasPlottableHistory(POPULATED)).toBe(true);
  });

  it("is false when the history is empty", () => {
    expect(hasPlottableHistory(EMPTY)).toBe(false);
  });

  it("is false when there are timestamps but no configured probes", () => {
    expect(hasPlottableHistory({ ...POPULATED, chart_data: [] })).toBe(false);
  });
});
