#!/usr/bin/env python3

# *****************************************
# PiFire Generic x86 Platform Interface Library
# *****************************************
#
# Description: This library controls PiFire outputs on generic x86 hardware.
#   Relays (power, igniter, auger, fan) are driven by a Numato USB relay board
#   over a serial (tty) device.  Fan PWM is generated by an EMC2101 fan
#   controller reached over the I2C bus exposed by a CP2112 USB-to-I2C bridge.
#
#   The fan is wired DC-fan-style: a relay gates fan power and the EMC2101
#   sets the fan speed.
#
# *****************************************

"""
	==============================
	  Imported Libraries
	==============================
"""

import glob
import os
import threading

from common import is_float, create_logger, get_os_info

from adafruit_extended_bus import ExtendedI2C
from adafruit_emc2101 import EMC2101

from grillplat.numato_usbrelay import NumatoUSBRelay


"""
	==============================
	  Module Helpers
	==============================
"""

def find_i2c_bus(match='CP2112', devices_path='/sys/bus/i2c/devices'):
	"""
	Find the integer i2c bus number whose adapter name contains `match`.

	Scans `<devices_path>/i2c-*/name`.  Raises RuntimeError if zero or more
	than one adapter matches, so the caller can fail clearly.
	"""
	match_lower = match.lower()
	found = []
	for bus_dir in glob.glob(os.path.join(devices_path, 'i2c-*')):
		name_file = os.path.join(bus_dir, 'name')
		try:
			with open(name_file) as handle:
				name = handle.read().strip()
		except OSError:
			continue
		if match_lower in name.lower():
			# Bus number is the trailing integer of the i2c-N directory name.
			try:
				bus_num = int(os.path.basename(bus_dir).split('-')[-1])
			except ValueError:
				continue
			found.append(bus_num)

	if len(found) == 1:
		return found[0]
	if not found:
		raise RuntimeError(f'No i2c adapter found matching {match!r} under {devices_path}')
	raise RuntimeError(f'Multiple i2c adapters match {match!r}: {sorted(found)}')
