#!/usr/bin/env python3

# *****************************************
# PiFire Generic x86 Platform Interface Library
# *****************************************
#
# Description: This library controls PiFire outputs on generic x86 hardware.
#   Relays (power, igniter, auger, fan) are driven by a Numato USB relay board
#   over a serial (tty) device.  Fan PWM is generated by an EMC2101 fan
#   controller reached over an I2C bus.  The bus is selectable (matching the
#   probe drivers' scheme): 'basic' uses the board's integrated I2C bus, while
#   'extended' uses a numbered /dev/i2c-N bus or a USB-to-I2C bridge (e.g. a
#   CP2112) discovered by adapter-name match.
#
#   The fan is wired DC-fan-style: a relay gates fan power and the EMC2101
#   sets the fan speed.
#
# *****************************************

"""
	==============================
	  Imported Libraries
	==============================
"""

import glob
import os
import threading

from common import is_float, create_logger, get_os_info

import board
import busio
from adafruit_extended_bus import ExtendedI2C
from adafruit_emc2101 import EMC2101

from grillplat.numato_usbrelay import NumatoUSBRelay


"""
	==============================
	  Module Helpers
	==============================
"""

def find_i2c_bus(match='CP2112', devices_path='/sys/bus/i2c/devices'):
	"""
	Find the integer i2c bus number whose adapter name contains `match`.

	Scans `<devices_path>/i2c-*/name`.  Raises RuntimeError if zero or more
	than one adapter matches, so the caller can fail clearly.
	"""
	match_lower = match.lower()
	found = []
	for bus_dir in glob.glob(os.path.join(devices_path, 'i2c-*')):
		name_file = os.path.join(bus_dir, 'name')
		try:
			with open(name_file) as handle:
				name = handle.read().strip()
		except OSError:
			continue
		if match_lower in name.lower():
			# Bus number is the trailing integer of the i2c-N directory name.
			try:
				bus_num = int(os.path.basename(bus_dir).split('-')[-1])
			except ValueError:
				continue
			found.append(bus_num)

	if len(found) == 1:
		return found[0]
	if not found:
		raise RuntimeError(f'No i2c adapter found matching {match!r} under {devices_path}')
	raise RuntimeError(f'Multiple i2c adapters match {match!r}: {sorted(found)}')


def resolve_i2c_bus(bus):
	"""
	Resolve an extended-i2c-bus spec to a bus number. Accepts an int or numeric
	string (e.g. 3 / '3' -> /dev/i2c-3, used directly) or an adapter-name match
	string (e.g. 'CP2112' -> discovered via find_i2c_bus, robust against the
	dynamic bus numbers USB-to-I2C bridges get).

	Mirrors probes.base.resolve_i2c_bus so probes and the platform driver share
	the same basic/extended bus conventions.
	"""
	spec = str(bus).strip()
	# A plain number is a /dev/i2c-N bus index; anything else is an adapter-name
	# match. Check explicitly (rather than try/int/except) so a name like 'CP2112'
	# does not raise a ValueError -- only find_i2c_bus's clear "not found" error
	# can surface.
	if spec.isdigit():
		return int(spec)
	return find_i2c_bus(spec)


"""
	==============================
	  Class Definition
	==============================
"""

# Default Numato relay index for each PiFire output.
_DEFAULT_OUTPUTS = {'power': 0, 'igniter': 1, 'auger': 2, 'fan': 3}


class GrillPlatform:

	def __init__(self, config):
		self.logger = create_logger('control')
		self.config = config

		outputs = config.get('outputs', {}) or {}
		self.relay_map = {
			name: int(outputs.get(name, default))
			for name, default in _DEFAULT_OUTPUTS.items()
		}

		numato_cfg = config.get('numato', {}) or {}
		self.device = numato_cfg.get('device', '/dev/ttyACM0')
		self.baudrate = int(numato_cfg.get('baudrate', 921600))

		emc_cfg = config.get('emc2101', {}) or {}
		# I2C bus selection, matching the probe drivers' basic/extended scheme:
		#   'basic'    -> the board's integrated I2C bus (board.SCL/SDA)
		#   'extended' -> a numbered /dev/i2c-N bus, or a USB-to-I2C bridge
		#                 (e.g. a CP2112) discovered by adapter-name match.
		if 'i2c_bus_kind' in emc_cfg:
			self.i2c_bus_kind = emc_cfg['i2c_bus_kind']
		elif 'i2c_bus_match' in emc_cfg:
			# Legacy config (pre basic/extended): the EMC2101 lived on a CP2112
			# bridge, so honor it as an extended bus rather than silently
			# switching the install to the integrated bus.
			self.i2c_bus_kind = 'extended'
		else:
			self.i2c_bus_kind = 'basic'
		self.i2c_bus_num = emc_cfg.get('i2c_bus_num', emc_cfg.get('i2c_bus_match', 'CP2112'))
		address = emc_cfg.get('address', 0x4c)
		if isinstance(address, str):
			address = int(address, 16)
		self.emc_address = address

		self.frequency = config.get('frequency', 100)
		self.standalone = config.get('standalone', True)

		# Cached commanded output state (avoids a serial round-trip per poll).
		self._output_state = {'auger': False, 'fan': False, 'igniter': False, 'power': False}
		self._fan_speed_percent = 0

		# Fan ramp control.
		self._ramp_thread = None
		self._ramp_stop = threading.Event()

		# Open the relay board.
		self.relay = NumatoUSBRelay(self.device, baudrate=self.baudrate)

		# Open the EMC2101 on the configured I2C bus.
		if self.i2c_bus_kind == 'extended':
			i2c = ExtendedI2C(resolve_i2c_bus(self.i2c_bus_num))
		else:
			i2c = busio.I2C(board.SCL, board.SDA)
		self.emc = EMC2101(i2c)

		# Start in a known state: all relays off, fan stopped.
		self.relay.reset()
		self.emc.manual_fan_speed = 0

	# MARK: Output control
	def _set_output(self, name, state):
		# Call relay_on/relay_off directly (not relay_set) so the action is
		# explicit and observable when the relay driver is mocked in tests.
		index = self.relay_map[name]
		if state:
			self.relay.relay_on(index)
		else:
			self.relay.relay_off(index)
		self._output_state[name] = state

	def auger_on(self):
		self.logger.debug('auger_on: Turning on auger')
		self._set_output('auger', True)

	def auger_off(self):
		self.logger.debug('auger_off: Turning off auger')
		self._set_output('auger', False)

	def igniter_on(self):
		self.logger.debug('igniter_on: Turning on igniter')
		self._set_output('igniter', True)

	def igniter_off(self):
		self.logger.debug('igniter_off: Turning off igniter')
		self._set_output('igniter', False)

	def power_on(self):
		self.logger.debug('power_on: Powering on grill platform')
		self._set_output('power', True)

	def power_off(self):
		self.logger.debug('power_off: Powering off grill platform')
		self._set_output('power', False)

	def get_input_status(self):
		# No selector/shutdown inputs on this platform.
		return False

	# MARK: Fan / PWM control
	def fan_on(self, fan_speed_percent=100):
		self.logger.debug('fan_on: Enabling fan power and setting speed to ' + str(fan_speed_percent))
		self.relay.relay_on(self.relay_map['fan'])
		self._output_state['fan'] = True
		self._stop_ramp()
		self.set_duty_cycle(fan_speed_percent)

	def fan_off(self):
		self.logger.debug('fan_off: Stopping fan and removing power')
		self._stop_ramp()
		self.emc.manual_fan_speed = 0
		self._fan_speed_percent = 0
		self.relay.relay_off(self.relay_map['fan'])
		self._output_state['fan'] = False

	def fan_toggle(self):
		if self._output_state['fan']:
			self.fan_off()
		else:
			self.fan_on()

	def set_duty_cycle(self, fan_speed_percent, override_ramping=True):
		# Called by control.py (override_ramping=True) and by the ramp thread
		# (override_ramping=False so it does not stop the thread it runs in).
		if override_ramping:
			self._stop_ramp()
		# Clamp to the EMC2101's valid 0-100 range.  manual_fan_speed raises
		# ValueError outside that range; an out-of-range settings value would
		# otherwise kill the ramp thread silently mid-ramp.
		fan_speed_percent = max(0, min(100, fan_speed_percent))
		# EMC2101 duty maps directly to fan speed percent (no inversion).
		self.emc.manual_fan_speed = fan_speed_percent
		self._fan_speed_percent = fan_speed_percent

	def set_pwm_frequency(self, frequency=100):
		self.logger.debug('set_pwm_frequency: Setting PWM frequency to ' + str(frequency))
		self.frequency = frequency
		# Best-effort: apply to the EMC2101 if the library exposes the property.
		if hasattr(self.emc, 'pwm_frequency'):
			try:
				self.emc.pwm_frequency = frequency
			except (ValueError, OSError) as exc:
				self.logger.warning('set_pwm_frequency: EMC2101 rejected frequency: ' + str(exc))

	def _stop_ramp(self):
		# Stop any in-progress fan ramp. The fan methods above call it; the
		# ramp-start methods (added in a later task) reuse it. Safe to call when
		# no ramp is running (self._ramp_thread is None).
		if self._ramp_thread is not None:
			self._ramp_stop.set()
			if self._ramp_thread is not threading.current_thread():
				self._ramp_thread.join(timeout=5)
			self._ramp_thread = None

	# MARK: Fan ramp (Smoke Plus)
	def pwm_fan_ramp(self, on_time=5, min_duty_cycle=20, max_duty_cycle=100):
		self.logger.debug('pwm_fan_ramp: Starting fan ramp on_time=' + str(on_time) +
			' min=' + str(min_duty_cycle) + ' max=' + str(max_duty_cycle))
		self.relay.relay_on(self.relay_map['fan'])
		self._output_state['fan'] = True
		self._start_ramp(on_time, min_duty_cycle, max_duty_cycle)

	def _start_ramp(self, on_time, min_duty_cycle, max_duty_cycle):
		self._stop_ramp()
		self._ramp_stop = threading.Event()
		self._ramp_thread = threading.Thread(
			target=self._ramp_device,
			args=(on_time, min_duty_cycle, max_duty_cycle),
			daemon=True,
		)
		self._ramp_thread.start()

	def _ramp_device(self, on_time, min_duty_cycle, max_duty_cycle, fps=25):
		# Linearly ramp the fan speed from min to max over on_time seconds.
		# No inversion: values are fan-speed percent applied directly.
		steps = max(int(fps * on_time), 1)
		for i in range(steps):
			fraction = i / steps
			percent = min_duty_cycle + (max_duty_cycle - min_duty_cycle) * fraction
			self.set_duty_cycle(round(percent, 2), override_ramping=False)
			if self._ramp_stop.wait(1.0 / fps):
				break
		self.set_duty_cycle(max_duty_cycle, override_ramping=False)

	# MARK: Lifecycle
	def cleanup(self):
		self.logger.debug('cleanup: Shutting down outputs')
		self._stop_ramp()
		try:
			self.emc.manual_fan_speed = 0
		except Exception:
			pass
		try:
			self.relay.reset()
		finally:
			self.relay.close()

	# MARK: System / Platform Commands
	def supported_commands(self, arglist):
		supported_commands = [
			'check_throttled',
			'check_wifi_quality',
			'check_cpu_temp',
			'supported_commands',
			'check_alive',
			'scan_bluetooth',
			'os_info',
			'network_info',
			'hardware_info',
		]
		return {
			'result': 'OK',
			'message': 'Supported commands listed in "data".',
			'data': {'supported_cmds': supported_commands},
		}

	def check_throttled(self, arglist):
		# Not applicable on x86 hardware.
		return {
			'result': 'OK',
			'message': 'No under-voltage or throttling detected.',
			'data': {'cpu_under_voltage': False, 'cpu_throttled': False},
		}

	def check_cpu_temp(self, arglist):
		import psutil
		temp = 0.0
		result = 'OK'
		message = 'Successfully obtained CPU temperature.'
		try:
			sensors = psutil.sensors_temperatures()
			readings = []
			for label in ('coretemp', 'k10temp', 'cpu_thermal', 'acpitz'):
				if sensors.get(label):
					readings = sensors[label]
					break
			if not readings:
				for entries in sensors.values():
					if entries:
						readings = entries
						break
			if readings:
				temp = float(readings[0].current)
			else:
				message = 'No CPU temperature sensors available.'
		except Exception as exc:
			result = 'ERROR'
			message = 'Error obtaining CPU temperature: ' + str(exc)
		if not is_float(str(temp)):
			temp = 0.0
		return {
			'result': result,
			'message': message,
			'data': {'cpu_temp': float(temp)},
		}

	def check_wifi_quality(self, arglist):
		import subprocess
		data = {'result': 'ERROR', 'message': 'Unable to obtain wifi quality data.', 'data': {}}
		try:
			output = subprocess.check_output(['iwconfig'])
			lines = output.decode('utf-8').splitlines()
			for line in lines:
				if 'Link Quality=' in line:
					quality_str = line.split('=')[1].strip()
					quality_parts = quality_str.split(' ')[0]
					try:
						quality_value, quality_max = quality_parts.split('/')
						percentage = (int(quality_value) / int(quality_max)) * 100
						data['result'] = 'OK'
						data['message'] = 'Successfully obtained wifi quality data.'
						data['data']['wifi_quality_value'] = int(quality_value)
						data['data']['wifi_quality_max'] = int(quality_max)
						data['data']['wifi_quality_percentage'] = round(percentage, 2)
					except ValueError:
						pass
		except Exception:
			pass
		return data

	def check_alive(self, arglist):
		return {
			'result': 'OK',
			'message': 'The control script is running.',
			'data': {},
		}

	def scan_bluetooth(self, arglist):
		import asyncio
		try:
			from bleak import BleakScanner
		except ImportError:
			return {
				'result': 'ERROR',
				'message': 'bleak is not installed. Run: pip install bleak',
				'data': {'bt_devices': []},
			}

		bt_devices = []
		result = 'OK'
		message = 'Bluetooth scan completed successfully.'

		async def _scan():
			discovered = await BleakScanner.discover(timeout=5.0)
			for dev in discovered:
				name = dev.name or 'Unknown'
				bt_devices.append({'name': name, 'hw_id': dev.address.lower(), 'info': ''})

		try:
			asyncio.run(_scan())
		except Exception as exc:
			result = 'ERROR'
			message = 'Bluetooth scan error: ' + str(exc)
			self.logger.error('scan_bluetooth: Error during scan - ' + str(exc))

		return {
			'result': result,
			'message': message,
			'data': {'bt_devices': bt_devices},
		}

	def os_info(self, arglist):
		return {
			'result': 'OK',
			'message': 'OS information retrieved successfully.',
			'data': get_os_info(),
		}

	def network_info(self, arglist):
		import netifaces
		net_info = {}
		for iface in netifaces.interfaces():
			addrs = netifaces.ifaddresses(iface)
			ip_addr = addrs.get(netifaces.AF_INET, [{}])[0].get('addr', 'N/A')
			mac_addr = addrs.get(netifaces.AF_LINK, [{}])[0].get('addr', 'N/A')
			net_info[iface] = {'ip_address': ip_addr, 'mac_address': mac_addr}
		return {
			'result': 'OK',
			'message': 'Network information retrieved successfully.',
			'data': net_info,
		}

	def hardware_info(self, arglist):
		import psutil
		cpu_info = {
			'hardware': 'Unknown',
			'model': 'Unknown',
			'model_name': 'Unknown',
			'cores': psutil.cpu_count(logical=True),
			'frequency': psutil.cpu_freq().current if psutil.cpu_freq() else 'Unknown',
		}
		try:
			with open('/proc/cpuinfo') as f:
				for line in f:
					if 'model name' in line.lower():
						cpu_info['model_name'] = line.strip().split(':')[1].strip()
		except OSError:
			pass
		mem_info = psutil.virtual_memory()
		return {
			'result': 'OK',
			'message': 'Hardware information retrieved successfully.',
			'data': {
				'cpu_info': cpu_info,
				'total_ram': mem_info.total,
				'available_ram': mem_info.available,
			},
		}

	def get_output_status(self):
		self.current = {
			'auger': self._output_state['auger'],
			'igniter': self._output_state['igniter'],
			'power': self._output_state['power'],
			'fan': self._output_state['fan'],
			'pwm': self._fan_speed_percent,
			'frequency': self.frequency,
		}
		return self.current
