#!/usr/bin/env python3

# *****************************************
# PiFire Generic x86 Platform Interface Library
# *****************************************
#
# Description: This library controls PiFire outputs on generic x86 hardware.
#   Relays (power, igniter, auger, fan) are driven by a Numato USB relay board
#   over a serial (tty) device.  Fan PWM is generated by an EMC2101 fan
#   controller reached over the I2C bus exposed by a CP2112 USB-to-I2C bridge.
#
#   The fan is wired DC-fan-style: a relay gates fan power and the EMC2101
#   sets the fan speed.
#
# *****************************************

"""
	==============================
	  Imported Libraries
	==============================
"""

import glob
import os
import threading

from common import is_float, create_logger, get_os_info

from adafruit_extended_bus import ExtendedI2C
from adafruit_emc2101 import EMC2101

from grillplat.numato_usbrelay import NumatoUSBRelay


"""
	==============================
	  Module Helpers
	==============================
"""

def find_i2c_bus(match='CP2112', devices_path='/sys/bus/i2c/devices'):
	"""
	Find the integer i2c bus number whose adapter name contains `match`.

	Scans `<devices_path>/i2c-*/name`.  Raises RuntimeError if zero or more
	than one adapter matches, so the caller can fail clearly.
	"""
	match_lower = match.lower()
	found = []
	for bus_dir in glob.glob(os.path.join(devices_path, 'i2c-*')):
		name_file = os.path.join(bus_dir, 'name')
		try:
			with open(name_file) as handle:
				name = handle.read().strip()
		except OSError:
			continue
		if match_lower in name.lower():
			# Bus number is the trailing integer of the i2c-N directory name.
			try:
				bus_num = int(os.path.basename(bus_dir).split('-')[-1])
			except ValueError:
				continue
			found.append(bus_num)

	if len(found) == 1:
		return found[0]
	if not found:
		raise RuntimeError(f'No i2c adapter found matching {match!r} under {devices_path}')
	raise RuntimeError(f'Multiple i2c adapters match {match!r}: {sorted(found)}')


"""
	==============================
	  Class Definition
	==============================
"""

# Default Numato relay index for each PiFire output.
_DEFAULT_OUTPUTS = {'power': 0, 'igniter': 1, 'auger': 2, 'fan': 3}


class GrillPlatform:

	def __init__(self, config):
		self.logger = create_logger('control')
		self.config = config

		outputs = config.get('outputs', {}) or {}
		self.relay_map = {
			name: int(outputs.get(name, default))
			for name, default in _DEFAULT_OUTPUTS.items()
		}

		numato_cfg = config.get('numato', {}) or {}
		self.device = numato_cfg.get('device', '/dev/ttyACM0')
		self.baudrate = int(numato_cfg.get('baudrate', 921600))

		emc_cfg = config.get('emc2101', {}) or {}
		self.i2c_bus_match = emc_cfg.get('i2c_bus_match', 'CP2112')
		address = emc_cfg.get('address', 0x4c)
		if isinstance(address, str):
			address = int(address, 16)
		self.emc_address = address

		self.frequency = config.get('frequency', 100)
		self.standalone = config.get('standalone', True)

		# Cached commanded output state (avoids a serial round-trip per poll).
		self._output_state = {'auger': False, 'fan': False, 'igniter': False, 'power': False}
		self._fan_speed_percent = 0

		# Fan ramp control.
		self._ramp_thread = None
		self._ramp_stop = threading.Event()

		# Open the relay board.
		self.relay = NumatoUSBRelay(self.device, baudrate=self.baudrate)

		# Open the EMC2101 on the CP2112 bridge bus.
		bus_num = find_i2c_bus(match=self.i2c_bus_match)
		self.emc = EMC2101(ExtendedI2C(bus_num))

		# Start in a known state: all relays off, fan stopped.
		self.relay.reset()
		self.emc.manual_fan_speed = 0

	# MARK: Output control
	def _set_output(self, name, state):
		# Call relay_on/relay_off directly (not relay_set) so the action is
		# explicit and observable when the relay driver is mocked in tests.
		index = self.relay_map[name]
		if state:
			self.relay.relay_on(index)
		else:
			self.relay.relay_off(index)
		self._output_state[name] = state

	def auger_on(self):
		self.logger.debug('auger_on: Turning on auger')
		self._set_output('auger', True)

	def auger_off(self):
		self.logger.debug('auger_off: Turning off auger')
		self._set_output('auger', False)

	def igniter_on(self):
		self.logger.debug('igniter_on: Turning on igniter')
		self._set_output('igniter', True)

	def igniter_off(self):
		self.logger.debug('igniter_off: Turning off igniter')
		self._set_output('igniter', False)

	def power_on(self):
		self.logger.debug('power_on: Powering on grill platform')
		self._set_output('power', True)

	def power_off(self):
		self.logger.debug('power_off: Powering off grill platform')
		self._set_output('power', False)

	def get_input_status(self):
		# No selector/shutdown inputs on this platform.
		return False

	def get_output_status(self):
		self.current = {
			'auger': self._output_state['auger'],
			'igniter': self._output_state['igniter'],
			'power': self._output_state['power'],
			'fan': self._output_state['fan'],
		}
		return self.current
