"""Narrow structural contracts for persistence consumers."""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from os import PathLike
from typing import TYPE_CHECKING, Protocol, TypeAlias


if TYPE_CHECKING:
    from common.common import ErrorKind
    from common.control_trace import ControlTraceRecord
    from common.current_schema import CurrentSnapshot
    from common.model_evidence import EvidenceKind, ModelEvidenceRecord

JsonScalar: TypeAlias = str | int | float | bool | None
JsonValue: TypeAlias = JsonScalar | Mapping[str, "JsonValue"] | Sequence["JsonValue"]
JsonDocument: TypeAlias = dict[str, JsonValue]
JsonMapping: TypeAlias = Mapping[str, JsonValue]
QueueValue: TypeAlias = JsonValue


class PersistentQueue(Protocol):
    def push(self, item: QueueValue) -> None: ...

    def pop(self) -> QueueValue | None: ...

    def length(self) -> int: ...

    def list(self) -> list[QueueValue]: ...

    def flush(self) -> None: ...

    def drain(self) -> list[QueueValue]: ...


class ControlPersistence(Protocol):
    def read_control(self) -> JsonDocument: ...
    def ensure_cook_id(self, *, preferred: str | None = None) -> str: ...

    def flush_control(self, *, cook_id: str | None = None) -> JsonDocument: ...

    def write_control_snapshot(self, control: JsonMapping, *, origin: str = "control") -> None: ...

    def enqueue_control_delta(self, delta: JsonMapping, *, origin: str = "control") -> None: ...

    def read_pending_control_writes(self) -> tuple[JsonDocument, ...]: ...

    def execute_control_writes(self) -> str | None: ...

    def mpc_calibration_command_state(
        self,
        control: JsonMapping | None = None,
        pending_writes: Sequence[JsonMapping] | None = None,
    ) -> JsonDocument | None: ...

    def mpc_calibration_command_revision(
        self,
        control: JsonMapping | None = None,
        pending_writes: Sequence[JsonMapping] | None = None,
    ) -> int: ...

    def queue_mpc_calibration_command(self, delta: JsonMapping, command: JsonMapping, origin: str) -> bool: ...


class RuntimePersistence(Protocol):
    def read_settings(self) -> JsonDocument: ...

    def write_settings(self, settings: JsonMapping) -> None: ...

    def read_pellet_db(self) -> JsonDocument: ...

    def write_pellet_db(self, db: JsonMapping) -> None: ...

    def read_status(self) -> JsonDocument: ...

    def init_status(self) -> JsonDocument: ...

    def write_status(self, status: JsonMapping) -> None: ...

    def read_current(self) -> JsonDocument: ...

    def read_current_snapshot(self) -> CurrentSnapshot: ...

    def flush_current(self) -> JsonDocument: ...

    def write_current(self, in_data: JsonMapping) -> None: ...

    def read_errors(self, kind: ErrorKind) -> list[str]: ...

    def flush_errors(self, kind: ErrorKind) -> list[str]: ...

    def write_errors(self, kind: ErrorKind, errors: Sequence[str]) -> None: ...

    def read_generic_key(self, key: str) -> JsonValue: ...

    def write_generic_key(self, key: str, value: JsonValue) -> None: ...


class HistoryPersistence(Protocol):
    def read_history(self, num_items: int = 0) -> list[JsonDocument]: ...

    def flush_history(self) -> None: ...

    def write_history(self, in_data: JsonMapping, maxsizelines: int = 28_800, ext_data: bool = False) -> None: ...

    def read_metrics(self) -> JsonDocument: ...

    def read_all_metrics(self) -> list[JsonDocument]: ...

    def flush_metrics(self) -> None: ...

    def append_metric(self, metrics: JsonMapping | None = None) -> None: ...

    def update_metrics(self, metrics: JsonMapping) -> None: ...

    def write_tr(self, tr: JsonValue) -> None: ...

    def read_tr(self) -> list[JsonValue]: ...

    def write_autotune(self, data: JsonValue) -> None: ...

    def read_autotune(self) -> list[JsonValue]: ...

    def autotune_length(self) -> int: ...

    def flush_autotune(self) -> None: ...


class TracePersistence(Protocol):
    def append_control_trace(self, records: Sequence[ControlTraceRecord]) -> None: ...

    def read_control_trace_session(
        self, session_id: str, *, database_path: str | PathLike[str] | None = None
    ) -> list[ControlTraceRecord]: ...

    def read_control_trace_cook(
        self, cook_id: str, *, database_path: str | PathLike[str] | None = None
    ) -> list[ControlTraceRecord]: ...

    def read_control_trace_range(self, start_ms: int, end_ms: int, *, limit: int) -> list[ControlTraceRecord]: ...

    def prune_control_trace(self, before_ms: int, *, limit: int) -> int: ...

    def prune_incompatible_control_trace(self, before_schema_version: int, *, limit: int) -> int: ...

    def delete_control_trace_session(self, session_id: str) -> int: ...


class ModelEvidencePersistence(Protocol):
    def append_model_evidence(
        self,
        records: Sequence[ModelEvidenceRecord],
        *,
        database_path: str | PathLike[str] | None = None,
    ) -> None: ...

    def read_model_evidence(
        self,
        *,
        session_id: str | None = None,
        cook_id: str | None = None,
        kind: EvidenceKind | None = None,
        database_path: str | PathLike[str] | None = None,
    ) -> list[ModelEvidenceRecord]: ...

    def commit_model_activation(
        self,
        decision: ModelEvidenceRecord,
        *,
        database_path: str | PathLike[str] | None = None,
    ) -> None: ...

    def reset_model_evidence(self, *, database_path: str | PathLike[str] | None = None) -> None: ...

    def invalidate_model_evidence_schema(self, *, database_path: str | PathLike[str] | None = None) -> None: ...


class _ControllerControlPersistence(Protocol):
    def read_control(self) -> JsonDocument: ...
    def ensure_cook_id(self, *, preferred: str | None = None) -> str: ...

    def flush_control(self, *, cook_id: str | None = None) -> JsonDocument: ...

    def write_control_snapshot(self, control: JsonMapping, *, origin: str = "control") -> None: ...

    def execute_control_writes(self) -> str | None: ...


class _ControllerRuntimePersistence(Protocol):
    def read_settings(self) -> JsonDocument: ...

    def read_pellet_db(self) -> JsonDocument: ...

    def write_pellet_db(self, db: JsonMapping) -> None: ...

    def read_status(self) -> JsonDocument: ...

    def init_status(self) -> JsonDocument: ...

    def write_status(self, status: JsonMapping) -> None: ...

    def flush_current(self) -> JsonDocument: ...

    def write_current(self, in_data: JsonMapping) -> None: ...

    def read_errors(self, kind: ErrorKind) -> list[str]: ...

    def write_errors(self, kind: ErrorKind, errors: Sequence[str]) -> None: ...

    def read_generic_key(self, key: str) -> JsonValue: ...

    def write_generic_key(self, key: str, value: JsonValue) -> None: ...


class _ControllerHistoryPersistence(Protocol):
    def flush_history(self) -> None: ...

    def write_history(
        self,
        in_data: JsonMapping,
        maxsizelines: int = 28_800,
        ext_data: bool = False,
    ) -> None: ...

    def read_metrics(self) -> JsonDocument: ...

    def read_all_metrics(self) -> list[JsonDocument]: ...

    def append_metric(self, metrics: JsonMapping | None = None) -> None: ...

    def update_metrics(self, metrics: JsonMapping) -> None: ...

    def write_tr(self, tr: JsonValue) -> None: ...


class ControllerStore(
    _ControllerControlPersistence,
    _ControllerRuntimePersistence,
    _ControllerHistoryPersistence,
    Protocol,
):
    """Only the capabilities used by the controller runtime."""

    def save_model_checkpoint(self, name: str, snapshot: JsonMapping) -> bool: ...

    def system_commands(self) -> PersistentQueue: ...

    def system_output(self) -> PersistentQueue: ...

    def display_commands(self) -> PersistentQueue: ...
