import { describe, expect, it } from "@rstest/core";
import type { HistoryChartData } from "../../helpers/history/historyApi";
import { hasPlottableHistory, toChartInput } from "./historyAdapter";

// Mirrors a real prepare_chartdata result (generated by calling the Python
// function with a seeded history): every point's `x` equals the matching
// `time_labels` entry, targets/setpoints are separate datasets, and a probe
// disabled in Settings comes back with `hidden: true`.
const POPULATED: HistoryChartData = {
  time_labels: [1784942370612, 1784942373612, 1784942376612],
  chart_data: [
    {
      label: "Grill",
      borderColor: "rgb(0, 64, 255, 1)",
      hidden: false,
      data: [
        { x: 1784942370612, y: 100 },
        { x: 1784942373612, y: 110 },
        { x: 1784942376612, y: 120 },
      ],
    },
    {
      label: "Grill Target",
      borderColor: "rgb(0, 128, 255, 1)",
      hidden: false,
      data: [
        { x: 1784942370612, y: 225 },
        { x: 1784942373612, y: 225 },
        { x: 1784942376612, y: 225 },
      ],
    },
    {
      label: "Probe 1",
      borderColor: "#888",
      hidden: true,
      data: [
        { x: 1784942370612, y: 90 },
        { x: 1784942373612, y: 95 },
        { x: 1784942376612, y: 100 },
      ],
    },
  ],
  probe_mapper: { probes: { grill1: 0 }, targets: { grill1: 1 }, primarysp: {} },
  graph_labels: { probes: { grill1: "Grill" }, targets: { grill1: "Grill Target" }, primarysp: {} },
  annotations: {},
  minutes: 60,
};

const EMPTY: HistoryChartData = {
  time_labels: [],
  chart_data: [
    { label: "Grill", borderColor: "rgb(0, 64, 255, 1)", hidden: false, data: [] },
    { label: "Grill Target", borderColor: "rgb(0, 128, 255, 1)", hidden: false, data: [] },
  ],
  probe_mapper: { probes: { grill1: 0 }, targets: { grill1: 1 }, primarysp: {} },
  graph_labels: { probes: { grill1: "Grill" }, targets: { grill1: "Grill Target" }, primarysp: {} },
  annotations: {},
  minutes: 60,
};

describe("toChartInput", () => {
  it("converts epoch milliseconds to the epoch SECONDS HistoryChart expects", () => {
    // The single most consequential line in this module: uPlot's tooltip does
    // `new Date(x * 1000)`, so passing the API's milliseconds through
    // unchanged dates every sample ~50,000 years into the future while the
    // chart still draws a plausible-looking line.
    const { times } = toChartInput(POPULATED);

    expect(times).toEqual([1784942370.612, 1784942373.612, 1784942376.612]);
    expect(new Date(times[0] * 1000).toISOString()).toBe("2026-07-25T01:19:30.612Z");
    // What passing the raw milliseconds through would have produced:
    expect(new Date(POPULATED.time_labels[0] * 1000).getUTCFullYear()).toBeGreaterThan(50000);
  });

  it("maps each dataset's y values in time order", () => {
    const { series } = toChartInput(POPULATED);

    expect(series.map((s) => s.label)).toEqual(["Grill", "Grill Target"]);
    expect(series[0].values).toEqual([100, 110, 120]);
    expect(series[1].values).toEqual([225, 225, 225]);
  });

  it("carries each dataset's borderColor through as the series stroke", () => {
    expect(toChartInput(POPULATED).series[0].color).toBe("rgb(0, 64, 255, 1)");
  });

  it("falls back to a readable stroke when a dataset has no borderColor", () => {
    const noColor: HistoryChartData = {
      ...POPULATED,
      chart_data: [{ label: "Grill", data: POPULATED.chart_data[0].data }],
    };

    // Theme.dim / --text-dim. themeTokens.test.ts is what keeps this literal
    // and the token in step; this test only pins that the fallback is used.
    expect(toChartInput(noColor).series[0].color).toBe("#8a7f70");
  });

  it("drops hidden datasets (a probe disabled in Settings)", () => {
    const { series } = toChartInput(POPULATED);

    expect(series.map((s) => s.label)).not.toContain("Probe 1");
  });

  it("pads a dataset shorter than time_labels with nulls so uPlot stays aligned", () => {
    const ragged: HistoryChartData = {
      ...POPULATED,
      chart_data: [{ label: "Grill", data: [{ x: 1784942370612, y: 100 }] }],
    };

    const { times, series } = toChartInput(ragged);

    expect(series[0].values).toEqual([100, null, null]);
    expect(series[0].values.length).toBe(times.length);
  });

  it("keeps a null reading as a gap rather than turning it into zero", () => {
    const withGap: HistoryChartData = {
      ...POPULATED,
      chart_data: [
        {
          label: "Grill",
          data: [
            { x: 1784942370612, y: 100 },
            { x: 1784942373612, y: null },
            { x: 1784942376612, y: 120 },
          ],
        },
      ],
    };

    expect(toChartInput(withGap).series[0].values).toEqual([100, null, 120]);
  });

  it("returns empty arrays for an empty history instead of throwing", () => {
    const { times, series } = toChartInput(EMPTY);

    expect(times).toEqual([]);
    expect(series.map((s) => s.values)).toEqual([[], []]);
  });
});

describe("hasPlottableHistory", () => {
  it("is true for a payload with samples", () => {
    expect(hasPlottableHistory(POPULATED)).toBe(true);
  });

  it("is false when the history is empty", () => {
    expect(hasPlottableHistory(EMPTY)).toBe(false);
  });

  it("is false when there are timestamps but no configured probes", () => {
    expect(hasPlottableHistory({ ...POPULATED, chart_data: [] })).toBe(false);
  });
});
